quadrus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_back_right_hip
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_back_right_upperleg
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_back_right_lowerleg
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_back_left_hip
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_back_left_upperleg
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_back_left_lowerleg
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_front_right_hip
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_front_right_upperleg
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_front_right_lowerleg
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_front_left_hip
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_front_left_upperleg
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_front_left_lowerleg
    pid: {p: 100.0, i: 0.01, d: 10.0}
