joint_limits:
  J1:
    has_position_limits: true
    min_position: -0.524
    max_position: 0.785
  J2:
    has_position_limits: true
    min_position: -1.920
    max_position: 2.182
  J3:
    has_position_limits: true
    min_position: -1.309
    max_position: 2.356
  J4:
    has_position_limits: true
    min_position: -0.785
    max_position: 0.524
  J5:
    has_position_limits: true
    min_position: -2.182
    max_position: 1.920
  J6:
    has_position_limits: true
    min_position: -2.356
    max_position: 1.309
  J7:
    has_position_limits: true
    min_position: -0.524
    max_position: 0.785
  J8:
    has_position_limits: true
    min_position: -1.920
    max_position: 2.182
  J9:
    has_position_limits: true
    min_position: -1.309
    max_position: 2.356
  J10:
    has_position_limits: true
    min_position: -0.785
    max_position: 0.524
  J11:
    has_position_limits: true
    min_position: -2.182
    max_position: 1.920
  J12:
    has_position_limits: true
    min_position: -2.356
    max_position: 1.309