joint_limits:
  J1:
    has_position_limits: true
    min_position: 0.0
    max_position: 0.5
  J2:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.0
  J3:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.0
  J4:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.0
  J5:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.0
  J6:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.0
  J7:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.0
  J8:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.0
  J9:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.0
  J10:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.0
  J11:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.0
  J12:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.0