quadrus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Trajectory controller -------------------------------------
  leg_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
      - J7
      - J8
      - J9
      - J10
      - J11
      - J12
