quadrus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Trajectory controllers -------------------------------------
  leg_controller_1:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - J1
      - J2
      - J3

    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.02
      J1:
        goal: 0.02
      J2:
        goal: 0.01                   
      J3:
        goal: 0.01                    

    gains:
      J1: {p: 1000,  d: 10, i: 10, i_clamp: 100}
      J2: {p: 1000,  d: 10, i: 10, i_clamp: 100}
      J3: {p: 1000,  d: 10, i: 10, i_clamp: 100}

    state_publish_rate:  25            
    action_monitor_rate: 30           
    stop_trajectory_duration: 0