quadrus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Trajectory controllers -------------------------------------
  leg_controller_1:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - J1
      - J2
      - J3

    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.02
      J1:
        goal: 0.02
      J2:
        goal: 0.01                   
      J3:
        goal: 0.01                    

    state_publish_rate:  25     # a optimiser
    action_monitor_rate: 30     # a optimiser      
    stop_trajectory_duration: 0