quadrus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Trajectory controller -------------------------------------
  leg_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - J1

    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.02
      J1:
        goal: 0.03 #1.5-2 deg, correspond a l'erreur de lecture sur le pot                

    gains:
      J1: {p: 2000,  d: 1000, i: 0, i_clamp: 0}


    state_publish_rate:  25            
    action_monitor_rate: 20           
    stop_trajectory_duration: 0