quadrus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Trajectory controllers -------------------------------------
  leg_back_right_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - joint_back_right_hip
      - joint_back_right_upperleg
      - joint_back_right_lowerleg

    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.02
      joint_back_right_hip:
        goal: 0.02
      joint_back_right_upperleg:
        goal: 0.01                   
      joint_back_right_lowerleg:
        goal: 0.01                    

    gains:
      joint_back_right_hip: {p: 1000,  d: 10, i: 10, i_clamp: 100}
      joint_back_right_upperleg: {p: 1000,  d: 10, i: 10, i_clamp: 100}
      joint_back_right_lowerleg: {p: 1000,  d: 10, i: 10, i_clamp: 100}

    state_publish_rate:  25            
    action_monitor_rate: 30           
    stop_trajectory_duration: 0