quadrus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Trajectory controllers -------------------------------------
  leg_controller_1:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - J1
      - J2
      - J3

  leg_controller_2:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - J4
      - J5
      - J6

  leg_controller_3:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - J7
      - J8
      - J9

  leg_controller_4:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - J10
      - J11
      - J12
