quadrus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Trajectory controllers -------------------------------------
  leg_controller_1:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - J1
      - J2
      - J3

    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.02
      J1:
        goal: 0.02
      J2:
        goal: 0.01                   
      J3:
        goal: 0.01                    

    gains:
      J1: {p: 1000,  d: 10, i: 10, i_clamp: 100}
      J2: {p: 1000,  d: 10, i: 10, i_clamp: 100}
      J3: {p: 1000,  d: 10, i: 10, i_clamp: 100}

    state_publish_rate:  25            
    action_monitor_rate: 30           
    stop_trajectory_duration: 0

  leg_controller_2:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - J4
      - J5
      - J6

    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.02
      J4:
        goal: 0.02
      J5:
        goal: 0.01                   
      J6:
        goal: 0.01                    

    gains:
      J4: {p: 1000,  d: 10, i: 10, i_clamp: 100}
      J5: {p: 1000,  d: 10, i: 10, i_clamp: 100}
      J6: {p: 1000,  d: 10, i: 10, i_clamp: 100}

    state_publish_rate:  25            
    action_monitor_rate: 30           
    stop_trajectory_duration: 0

  leg_controller_3:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - J7
      - J8
      - J9

    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.02
      J7:
        goal: 0.02
      J8:
        goal: 0.01                   
      J9:
        goal: 0.01                    

    gains:
      J7: {p: 1000,  d: 10, i: 10, i_clamp: 100}
      J8: {p: 1000,  d: 10, i: 10, i_clamp: 100}
      J9: {p: 1000,  d: 10, i: 10, i_clamp: 100}

    state_publish_rate:  25            
    action_monitor_rate: 30           
    stop_trajectory_duration: 0

  leg_controller_4:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - J10
      - J11
      - J12

    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.02
      J10:
        goal: 0.02
      J11:
        goal: 0.01                   
      J12:
        goal: 0.01                    

    gains:
      J10: {p: 1000,  d: 10, i: 10, i_clamp: 100}
      J11: {p: 1000,  d: 10, i: 10, i_clamp: 100}
      J12: {p: 1000,  d: 10, i: 10, i_clamp: 100}

    state_publish_rate:  25            
    action_monitor_rate: 30           
    stop_trajectory_duration: 0