<?xml version='1.0'?>
<robot name="quadrus" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Constants for robot dimensions, mass and inertia-->
	<xacro:property name="PI" value="3.1415926535897931"/>
	
	<xacro:property name="hip_offset" value="2" /> 
	<xacro:property name="upperleg_length" value="1" /> 
	<xacro:property name="lowerleg_length" value="1" />

	<xacro:property name="rear_hip_long_offset" value="-0.12" /> 
	<xacro:property name="hip_long_center_dist" value="0.24" />
	<xacro:property name="hip_lat_center_dist" value="0.15" />
	

	<!-- Import Rviz colors -->
	<xacro:include filename="$(find simulation)/robot_description/materials.xacro" />

	<link name="base_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="0.30 0.10 0.07"/>
			</geometry>
			<material name="blue" />
		</visual>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="0.2 0.18 0.07"/>
			</geometry>
			<material name="blue"/>
		</visual>
		
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="0.30 0.10 0.07"/>
			</geometry>
		</collision>
	
		<inertial>
			<mass value="2"/>
			<inertia ixx="0.13" ixy="0.0" ixz="0.0" iyy="0.21" iyz="0.0" izz="0.13"/>
		</inertial>	

	</link>

	<xacro:macro name="quadrus_leg" params="long lat">
		<!-- Hip -->
			<link name="link_${long}_${lat}_hip">
				<visual>
					<origin xyz="0 0 0" rpy="0 0 0" />
					<geometry>
						<box size="0.03 0.05 0.03"/>
					</geometry>
					<material name="red"/>
				</visual>

				<collision>
					<origin xyz="0 0 0" rpy="0 0 0" />
					<geometry>
						<box size="0.03 0.05 0.03"/>
					</geometry>
				</collision>

				<inertial>
					<mass value="0.1"/>
					<inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
				</inertial>	

			</link>

			<joint name="joint_${long}_${lat}_hip" type="continuous">
				<parent link="base_link"/>
				<child link="link_${long}_${lat}_hip"/>

				<xacro:if value="${long == 'front' and lat == 'left'}">
					<origin xyz="${rear_hip_long_offset+hip_long_center_dist} ${hip_lat_center_dist/2.0} 0" rpy="0 0 0" /> 
				</xacro:if>

				<xacro:if value="${long == 'front' and lat == 'right'}">
					<origin xyz="${rear_hip_long_offset+hip_long_center_dist} ${-hip_lat_center_dist/2.0} 0" rpy="0 0 0" /> 
				</xacro:if>

				<xacro:if value="${long == 'back' and lat == 'left'}">
					<origin xyz="${rear_hip_long_offset} ${hip_lat_center_dist/2.0} 0" rpy="0 0 0" /> 
				</xacro:if>

				<xacro:if value="${long == 'back' and lat == 'right'}">
					<origin xyz="${rear_hip_long_offset} ${-hip_lat_center_dist/2.0} 0" rpy="0 0 0" /> 
				</xacro:if>

				<axis xyz="1 0 0" />
			</joint>

			<transmission name="transmission_${long}_${lat}_hip">
				<type>transmission_interface/SimpleTransmission</type>
				<joint name="joint_${long}_${lat}_hip">
					<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
				</joint>
				<actuator name="motor_${long}_${lat}_hip">
					<mechanicalReduction>1</mechanicalReduction>
					<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
				</actuator>
			</transmission>

			<gazebo reference="link_${long}_${lat}_hip">
				<material>Gazebo/Red</material>
			</gazebo>
		
		<!-- Upperleg -->
			<link name="link_${long}_${lat}_upperleg">
				<visual>
					<origin xyz="-0.075 0 0" rpy="0 0 0" />
					<geometry>
						<box size="0.18 0.03 0.03"/>
					</geometry>
					<material name="blue"/>
				</visual>
				
				<collision>
					<origin xyz="-0.075 0 0" rpy="0 0 0" />
					<geometry>
						<box size="0.18 0.03 0.03"/>
					</geometry>
				</collision>

				<inertial>
					<mass value="0.1"/>
					<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
				</inertial>

			</link>

			<joint name="joint_${long}_${lat}_upperleg" type="continuous">
				<parent link="link_${long}_${lat}_hip"/>
				<child link="link_${long}_${lat}_upperleg"/>

				<xacro:if value="${lat == 'left'}">
					<origin xyz="0 0.04 0" rpy="0 -0.7854 0" /> 
				</xacro:if>

				<xacro:if value="${lat == 'right'}">
					<origin xyz="0 -0.04 0" rpy="0 -0.7854 0" /> 
				</xacro:if>

				<axis xyz="0 1 0" />
			</joint>

			<transmission name="transmission_${long}_${lat}_upperleg">
				<type>transmission_interface/SimpleTransmission</type>
				<joint name="joint_${long}_${lat}_upperleg">
					<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
				</joint>
				<actuator name="motor_${long}_${lat}_upperleg">
					<mechanicalReduction>1</mechanicalReduction>
					<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
				</actuator>
			</transmission>

			<gazebo reference="link_${long}_${lat}_upperleg">
				<material>Gazebo/White</material>
			</gazebo>

		<!-- LowerLeg -->	
			<link name="link_${long}_${lat}_lowerleg">
				<visual>
					<origin xyz="0.075 0 0" rpy="0 0 0" />
					<geometry>
						<box size="0.18 0.03 0.03"/>
					</geometry>
					<material name="blue"/>
				</visual>
				
				<collision>
					<origin xyz="0.075 0 0" rpy="0 0 0" />
					<geometry>
						<box size="0.18 0.03 0.03"/>
					</geometry>
				</collision>

				<inertial>
					<mass value="0.1"/>
					<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
				</inertial>

			</link>

			<joint name="joint_${long}_${lat}_lowerleg" type="continuous">
				<parent link="link_${long}_${lat}_upperleg"/>
				<child link="link_${long}_${lat}_lowerleg"/>
				<origin xyz="-0.15 0 0" rpy="0 1.5708 0" /> 
				<axis xyz="0 1 0" />
			</joint>

			<transmission name="transmission_${long}_${lat}_lowerleg">
				<type>transmission_interface/SimpleTransmission</type>
				<joint name="joint_${long}_${lat}_lowerleg">
					<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
				</joint>
				<actuator name="motor_${long}_${lat}_lowerleg">
					<mechanicalReduction>1</mechanicalReduction>
					<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
				</actuator>
			</transmission>

			<gazebo reference="link_${long}_${lat}_lowerleg">
				<material>Gazebo/White</material>
			</gazebo>

		<!-- Paw -->	
			<link name="link_${long}_${lat}_paw">
				<visual>
					<origin xyz="0 0 0" rpy="0 0 0" />
					<geometry>
						<sphere radius = "0.03"/>
					</geometry>
					<material name="green"/>
				</visual>
				
				<collision>
					<origin xyz="0 0 0" rpy="0 0 0" />
					<geometry>
						<sphere radius = "0.03"/>
					</geometry>
				</collision>

				<inertial>
					<mass value="0.1"/>
					<inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
				</inertial>

			</link>

			<joint name="joint_${long}_${lat}_paw" type="fixed">
				<parent link="link_${long}_${lat}_lowerleg"/>
				<child link="link_${long}_${lat}_paw"/>
				<origin xyz="0.15 0 0" rpy="0 0 0" /> 
			</joint>

			<gazebo reference="link_${long}_${lat}_paw">
				<material>Gazebo/Green</material>
			</gazebo>
	
	</xacro:macro>

	<xacro:quadrus_leg long="back" lat="right"/>
	<xacro:quadrus_leg long="back" lat="left"/>
	<xacro:quadrus_leg long="front" lat="right"/>
	<xacro:quadrus_leg long="front" lat="left"/>

	<!-- Import all Gazebo-customization elements, including Gazebo colors -->
	<xacro:include filename="$(find simulation)/robot_description/quadrus.gazebo" />

</robot>